# Generated by Django 2.0.7 on 2018-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='uniq_count',
            field=models.IntegerField(default=0),
        ),
    ]
